services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: skn-backend-develop
    env_file:
      - ./backend/.env.production
    restart: always
    ports:
      - "127.0.0.1:8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: skn-frontend-develop
    env_file:
      - ./frontend/.env.production
    depends_on:
      - backend
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
