import type { Listing } from "@/components/room-finder/map-view"

export const mockListings: Listing[] = [
  {
    id: "1",
    title: "가산디지털단지역 도보 5분 신축 원룸",
    price: "월세",
    deposit: "500만원",
    monthlyRent: "45만원",
    address: "서울 금천구 가산동 123-45",
    size: "6평",
    floor: "3층/5층",
    images: ["/placeholder.svg?height=200&width=200"],
    lat: 37.4816,
    lng: 126.8828,
    structure: "오픈형",
    options: ["에어컨", "냉장고", "세탁기"],
  },
  {
    id: "2",
    title: "복층 원룸 창문 3개 남향",
    price: "월세",
    deposit: "1000만원",
    monthlyRent: "55만원",
    address: "서울 금천구 독산동 234-56",
    size: "8평",
    floor: "4층/6층",
    images: ["/placeholder.svg?height=200&width=200"],
    lat: 37.4789,
    lng: 126.8912,
    structure: "복층",
    options: ["에어컨", "냉장고", "세탁기", "인덕션"],
  },
  {
    id: "3",
    title: "역세권 분리형 원룸 풀옵션",
    price: "전세",
    deposit: "5000만원",
    monthlyRent: "",
    address: "서울 금천구 가산동 345-67",
    size: "7평",
    floor: "2층/4층",
    images: ["/placeholder.svg?height=200&width=200"],
    lat: 37.4823,
    lng: 126.8845,
    structure: "분리형",
    options: ["에어컨", "냉장고", "세탁기", "TV", "책상"],
  },
  {
    id: "4",
    title: "조용한 주택가 원룸",
    price: "월세",
    deposit: "300만원",
    monthlyRent: "40만원",
    address: "서울 금천구 시흥동 456-78",
    size: "5평",
    floor: "2층/3층",
    images: ["/placeholder.svg?height=200&width=200"],
    lat: 37.4756,
    lng: 126.8867,
    structure: "오픈형",
    options: ["에어컨"],
  },
  {
    id: "5",
    title: "대로변 신축 투룸",
    price: "월세",
    deposit: "2000만원",
    monthlyRent: "80만원",
    address: "서울 금천구 가산동 567-89",
    size: "12평",
    floor: "5층/10층",
    images: ["/placeholder.svg?height=200&width=200"],
    lat: 37.4834,
    lng: 126.8798,
    structure: "분리형",
    options: ["에어컨", "냉장고", "세탁기", "인덕션", "TV"],
  },
  {
    id: "6",
    title: "채광 좋은 남향 원룸",
    price: "전세",
    deposit: "4500만원",
    monthlyRent: "",
    address: "서울 금천구 독산동 678-90",
    size: "6평",
    floor: "3층/5층",
    images: ["/placeholder.svg?height=200&width=200"],
    lat: 37.4801,
    lng: 126.8923,
    structure: "오픈형",
    options: ["에어컨", "냉장고"],
  },
  {
    id: "7",
    title: "역 도보 3분 초역세권",
    price: "월세",
    deposit: "500만원",
    monthlyRent: "50만원",
    address: "서울 금천구 가산동 789-01",
    size: "5평",
    floor: "4층/7층",
    images: ["/placeholder.svg?height=200&width=200"],
    lat: 37.4812,
    lng: 126.8815,
    structure: "오픈형",
    options: ["에어컨", "세탁기"],
  },
  {
    id: "8",
    title: "넓은 복층 원룸 루프탑",
    price: "월세",
    deposit: "1500만원",
    monthlyRent: "70만원",
    address: "서울 금천구 시흥동 890-12",
    size: "10평",
    floor: "6층/6층",
    images: ["/placeholder.svg?height=200&width=200"],
    lat: 37.4745,
    lng: 126.8856,
    structure: "복층",
    options: ["에어컨", "냉장고", "세탁기", "인덕션", "TV", "책상"],
  },
]

// Mock embeddings for rooms (in real app, these would be computed from actual images)
export const mockRoomEmbeddings: Record<string, number[]> = {
  "1": Array.from({ length: 128 }, () => Math.random()),
  "2": Array.from({ length: 128 }, () => Math.random()),
  "3": Array.from({ length: 128 }, () => Math.random()),
  "4": Array.from({ length: 128 }, () => Math.random()),
  "5": Array.from({ length: 128 }, () => Math.random()),
  "6": Array.from({ length: 128 }, () => Math.random()),
  "7": Array.from({ length: 128 }, () => Math.random()),
  "8": Array.from({ length: 128 }, () => Math.random()),
}
